### ISSUE TITLE
소셜 로그인 추가 가능하신가요?

### ISSUE THREAD

**Issue by lee101570** [devITae/EBSOCProgressViewer#1]
소셜회원가입을 해서..
소셜로그인도 가능하시다면 추가 부탁드립니당..ㅠ

**Comment by devITae** [comment]
소셜 로그인 기능은 복잡해서 구현하지는 않았지만,
나중에 시간날 때 한번 시도는 해보도록 하겠습니다.

**Comment by devITae** [comment]
2021/04/30 지원 종료
