### ISSUE TITLE
기능 추가 요청: 수강신청되지 않은 강좌 목록

### ISSUE THREAD

**Issue by ilsubyeega** [devITae/EBSOCProgressViewer#4]
안녕하세요 현재도 유용하게 사용하고 있습니다!
혹시 수강신청되지 않은 강좌 목록을 확인할 수 있을까요? 가끔가다 중간에 수강신청을 놓치는 강좌들이 있어서 한번 요청해봅니다!

**Comment by devITae** [comment]
요청하신 기능은 v2.3 업데이트로 적용되었습니다! 
https://github.com/devITae/EBSOCProgressViewer/releases/tag/2.3
